version: "3.2"
services:
  app-site:
    build: .
    ports:
      - 9999:9999
    volumes:
      - ./:/webroot/default
    command: nodemon /webroot/default/index.js
  app-nginx:
    build: ./docker/nginx
    ports:
      - 8080:80
    links:
      - app-site:app-site
